apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello
  namespace: nju23
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: harbor.edu.cn/nju23/hello:{VERSION}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: nju23
  labels:
    app: hello
spec:

  selector:
    app: hello
  ports:
    - name: tcp
      nodePort: 40000
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: hello
  name: hello
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      port: tcp
      path: /actuator/prometheus
      scheme: 'http'
  selector:
    matchLabels:
      app: hello
  namespaceSelector:
    matchNames:
      - nju23
