apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  namespace: nju23
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: harbor.edu.cn/nju23/hello:{VERSION}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: bmp1MjM6bmp1MjMyMDIz

---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: nju23
spec:

  selector:
    app: hello
  ports:
    - port: 9090
      targetPort: 8080
  type: NodePort
