apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: nju23
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: harbor.edu.cn/nju23/hello:{VERSION}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: nju23
spec:

  selector:
    app: hello
  ports:
    - port: 9090
      targetPort: 8080
  type: NodePort
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: hello
  name: hello
  namespace: nju23
spec:
  endpoints:
    - interval: 30s
      port: tcp
      path: /actuator/prometheus
      scheme: 'http'
  selector:
    matchLabels:
      app: application
  namespaceSelector:
    matchNames:
      - nju23
